### ISSUE TITLE
Removing "style.css" after adding bootstrap in #17

### ISSUE THREAD

**Issue by Qw3rty26** [Lenigir-Srl/risto89#41]
style.css is currently not needed and can be safely removed, but only after PR #38 has been pushed.

**Comment by San7o** [comment]
I'll share the same comment I wrote for #41:

I disagree with this issue: It's best to keep one source for styling for the whole project, In order to leave every page consistent and requiring less work for styling each page. Some refactoring should be done with the current code base

Further comments are appreciated

**Comment by Qw3rty26** [comment]
I can see your point. Let's keep the `style.css` file for now and we'll come here again in the future if we need to ;)

Closing for now...
